site/app/urls.py
from re import DEBUG
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),  
    path('user/', include('users.urls', namespace='user')), 
    path('cart/', include('cart.urls', namespace='cart')), 
    path('orders/', include('orders.urls', namespace='orders')),   
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG :
    urlpatterns += debug_toolbar_urls() 

site/orders/urls.py
from django.urls import path

from . import views


app_name = "orders"

urlpatterns = [
    path("create-order/", views.create_order, name="create_order"),
]

site/orders/models.py
from django.db import models

from goods.models import Product
from users.models import User

# Create your models here.

class OrderitemQueryset(models.QuerySet):

 def total_price(self):
        return sum(cart.product_price() for cart in self)

def total_quantity(self):
    if self:
        return sum(cart.quantity for cart in self)
    return 0


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_DEFAULT, blank=True, null=True, default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=20)
    requires_delivery = models.BooleanField(default=False)
    delivery_address = models.TextField(null=True, blank=True)
    payment_on_get = models.BooleanField(default=False)
    is_paid = models.BooleanField(default=False)
    status = models.CharField(max_length=50, default="In process")

    class Meta:
        db_table = "Order"

    def __str__(self):
        return f"Order №{self.pk} | User {self.user.first_name} {self.user.last_name}"
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.SET_DEFAULT, null=True, default=None)
    name = models.CharField(max_length=150)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "order_item"

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.product.price_sale() * self.quantity, 2)
    
    def __str__(self):
        return f"Product {self.name} | Order №{self.order.pk}"

site/orders/forms.py
from django import forms

class CreateOrderForm(forms.Form):

    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    requires_delivery = forms.ChoiceField(
        choices=[
                ("0", False),
                ("1", True),
        ],)
    
    delivery_address = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(
        choices=[
                ("0", False),
                ("1", True),
        ],)


    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']

        if not data.isdigit():
            raise forms.ValidationError("Phone number should contain digits only")
        return data

site/orders/views.py
from django.contrib import messages
from django.db import transaction
from django.forms import ValidationError
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required

from cart.models import Cart
from orders.forms import CreateOrderForm
from orders.models import Order, OrderItem

# Create your views here.

@login_required
def create_order(request):
    if request.method == 'POST':
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    cart_items = Cart.objects.filter(user=user)
                    # Create order
                    if cart_items.exists():
                        order = Order.objects.create(
                            user=user,
                            phone_number=form.cleaned_data['phone_number'],
                            requires_delivery=form.cleaned_data['requires_delivery'],
                            delivery_address=form.cleaned_data['delivery_address'],
                            payment_on_get=form.cleaned_data['payment_on_get'],
                        )

                        # Create ordered products
                        for cart_item in cart_items:
                            product = cart_item.product
                            name = cart_item.product.name
                            price = cart_item.product.price_sale()
                            quantity = cart_item.quantity

                            if product.quantity < quantity:
                                raise ValidationError(f'Insufficient quantity {name} in stock\
                                                      Available {product.quantity}')
                            OrderItem.objects.create(
                                order=order,
                                product=product,
                                name=name,
                                price=price,
                                quantity=quantity,
                            )
                            product.quantity -= quantity
                            product.save()

                        # Clear the cart after successfull order
                        cart_item.delete()

                        messages.success(request, "Successfully ordered")
                        return redirect('user:profile')
            except ValidationError as e:
                messages.success(request, str(e))
                return redirect('orders:create_order')
    else:
        initial = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            }
        form = CreateOrderForm(initial=initial)
    
    context = {
        'form': form,
        'order': True,
    }
    return render(request, 'orders/create_order.html', context=context)
    

site/orders/templates/orders/create_order.html
{% extends "layout.html" %}
{% load static %}
{% load  cart_tags %}

{% block page_content %}
<div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
    <div class="container">
        <h3 class="text-center mb-4">Chosen products</h3>
        <div class="container" id="cart-items-container">
            <!-- Разметка корзины -->
            {% user_carts request as carts %}

            {% include "cart/include/included_cart.html" %}
            <!-- Закончилась разметка корзины -->
        </div>
    </div>
    <!-- Детали заказа -->
    <div class="container">
        <h3 class="text-center">Order details</h3>
        <div class="card mb-3">
            <div class="card-body">
                <form action="{% url "orders:create_order" %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">First name*:</label>
                            <input type="text" class="form-control" id="id_first_name"
                                value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                name="first_name" required>
                            {% if form.first_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Last name*:</label>
                            <input type="text" class="form-control" id="id_last_name" 
                                value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                name="last_name" required>
                            {% if form.last_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_phone_number" class="form-label">Phone number*:</label>
                            <input type="text" class="form-control" id="id_phone_number" name="phone_number"
                                value="{% if form.phone_number.value %}{{ form.phone_number.value }}{% endif %}"
                                placeholder="XXX-XXX-XX-XX"
                                required>
                            {% if form.phone_number.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.phone_number.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="delivery" class="form-label">Delivery method: </label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="requires_delivery"
                                    id="id_requires_delivery" value="1" checked>
                                <label class="form-check-label" for="id_requires_delivery">Delivery required</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="requires_delivery"
                                    id="id_requires_delivery" value="0">
                                <label class="form-check-label" for="id_requires_delivery">Self pickup</label>
                            </div>
                        </div>
                        <div class="mb-3" id="deliveryAddressField">
                            <label for="id_delivery_address" class="form-label">Delivery adress*:</label>
                            <textarea class="form-control" id="id_delivery_address"
                                value="{% if form.delivery_address.value %}{{ form.delivery_address.value }}{% endif %}"
                                name="delivery_address" rows="2"></textarea>
                            {% if form.delivery_address.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.delivery_address.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-12 mb-3">
                            <label class="form-label">Payment method: </label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="payment_on_get"
                                    id="id_payment_on_get" value="0" checked>
                                <label class="form-check-label" for="id_payment_on_get">Card pay</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="payment_on_get"
                                    id="id_payment_on_get" value="1">
                                <label class="form-check-label" for="id_payment_on_get">Cash/Card on delivery</label>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-dark">Finish order</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock page_content %}