site/app/urls.py
from re import DEBUG
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),  
    path('user/', include('users.urls', namespace='user')), 
    path('cart/', include('cart.urls', namespace='cart')), 
    path('orders/', include('orders.urls', namespace='orders')),   
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG :
    urlpatterns += debug_toolbar_urls() 

site/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
    ]

site/orders/urls.py
from django.urls import path

from . import views


app_name = "orders"

urlpatterns = [
    path("create-order/", views.create_order, name="create_order"),
]

site/cart/models.py
from django.db import models

from goods.models import Product
from users.models import User

class CartQuerySet(models.QuerySet):
    
    def total_price(self):
        return sum(cart.product_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Cart(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    session_key = models.CharField(max_length=32, null=True, blank=True)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    class Meta: 
        db_table = 'cart'

    objects = CartQuerySet().as_manager()

    def __str__(self):
        if self.user:
            return f'Cart of {self.user.username} | Product {self.product.name} | Quantity {self.quantity}'
        return f'Anonymous cart | Product {self.product.name} | Quantity {self.quantity}'

    def product_price(self):
        return round(self.product.price_sale() * self.quantity, 2)

site/cart/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string

from cart.models import Cart
from cart.utils import get_user_carts
from goods.models import Product
from users.views import users_cart


def cart_add(request):
    product_id = request.POST.get("product_id")
    product = Product.objects.get(id=product_id)
    
    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, product=product)

        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity +=1
                cart.save()
        else:
            Cart.objects.create(user=request.user, product=product, quantity=1)
    else:
        carts = Cart.objects.filter(
            session_key=request.session.session_key, product=product)

        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity +=1
                cart.save()
        else:
            Cart.objects.create(
                session_key=request.session.session_key, product=product, quantity=1)


    user_cart = get_user_carts(request)
    cart_items_html = render_to_string(
        'cart/include/included_cart.html', {"carts": user_cart}, request=request) 
          
    response_data = {
        "message": "Product added to cart",
        "cart_items_html": cart_items_html,
    }
    return JsonResponse(response_data)

def cart_change(request):
    cart_id = request.POST.get("cart_id")
    quantity = request.POST.get("quantity")

    cart = Cart.objects.get(id=cart_id)

    cart.quantity = quantity
    cart.save()
    updated_quantity = cart.quantity

    cart = get_user_carts(request)
    cart_items_html = render_to_string(
        "cart/include/included_cart.html", {"carts": cart}, request=request)
    
    response_data = {
        "message": "Quantity updated",
        "cart_items_html": cart_items_html,
        "quantity": updated_quantity,
    }
    return JsonResponse(response_data)


def cart_remove(request):
    cart_id = request.POST.get("cart_id")

    cart = Cart.objects.get(id=cart_id)
    quantity = cart.quantity
    cart.delete()

    user_cart = get_user_carts(request)
    cart_items_html = render_to_string(
        'cart/include/included_cart.html', {"carts": user_cart}, request=request) 
    response_data = {
        "message": "Product deleted",
        "cart_items_html": cart_items_html,
        "quantity_deleted": quantity,
    }
    return JsonResponse(response_data)
    

site/cart/templates/cart/include/included_cart.html
{% load static %}
{% load  cart_tags %}



<div class="card mb-3 text-bg-light shadow-lg">
{% user_carts request as carts %}
{% for cart in carts %}
    <div class="card-header">
        <h5 class="card-title">{{ cart.product.name }}</h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <div class="row text-center">
                <div class="col p-0">
                    <div class="input-group">
                        <span class="input-group-btn">
                            <button type="button" class="btn btn-dark btn-sm decrement"
                                data-cart-id="{{ cart.id }}" 
                                data-cart-change-url="{% url "cart:cart_change" %}">
                                {% csrf_token %}
                                -</button>
                        </span>
                        <input type="text" class="form-control number" value="{{ cart.quantity }}"
                            readonly>
                        <span class="input-group-btn">
                            <button type="button" class="btn btn-dark btn-sm increment"
                                data-cart-id="{{ cart.id }}" 
                                data-cart-change-url="{% url "cart:cart_change" %}">
                                {% csrf_token %}
                                +</button>
                        </span>
                    </div>
                </div>
                <div class="col p-0">
                    <p>{{ cart.product.price_sale }} = </p>
                </div>
                <div class="col p-0"><strong>{{ cart.product_price }}</strong></div>
                <div class="col p-0">
                    <a href="{% url "cart:cart_remove" %}" class="remove-from-cart" data-cart-id="{{ cart.id }}">
                        {% csrf_token %}
                        <img class="mx-1" src="{% static "files/icons/trash3-fill.svg"%}"
                            alt="Catalog Icon" width="16" height="16">
                    </a>
                </div>
            </div>
        </li>
    </ul>
{% endfor %}
</div>
<div class="card mb-3 shadow-lg">
    <div class="card-footer">
        <p class="float-left">Total <strong>{{ carts.total_quantity }}</strong> product(s)</p>
        <h4 class="float-left"><strong>{{ carts.total_price }}</strong></h4>
    </div>
</div>

{% if carts and not order%}
    <a class="btn btn-dark" href="{% url "orders:create_order" %}">
        Make order
    </a>
{% endif %}
                                