site/app/urls.py
from re import DEBUG
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),  
    path('user/', include('users.urls', namespace='user')), 
    path('cart/', include('cart.urls', namespace='cart')), 
    path('orders/', include('orders.urls', namespace='orders')),   
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG :
    urlpatterns += debug_toolbar_urls() 

site/goods/urls.py
from django.urls import path
from . import views

app_name='goods'

urlpatterns = [        
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),     
]

site/orders/urls.py
from django.urls import path

from . import views


app_name = "orders"

urlpatterns = [
    path("create-order/", views.create_order, name="create_order"),
]

site/users/urls.py
from django.urls import path
from . import views

app_name='users'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('registration', views.registration, name="registration"),
    path('profile', views.profile, name="profile"),
    path('logout', views.logout, name="logout"),
    path('users-cart/', views.users_cart, name="users_cart"),
]

site/orders/models.py
from django.db import models

from goods.models import Product
from users.models import User

# Create your models here.

class OrderitemQueryset(models.QuerySet):

 def total_price(self):
        return sum(cart.product_price() for cart in self)

def total_quantity(self):
    if self:
        return sum(cart.quantity for cart in self)
    return 0


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_DEFAULT, blank=True, null=True, default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=20)
    requires_delivery = models.BooleanField(default=False)
    delivery_address = models.TextField(null=True, blank=True)
    payment_on_get = models.BooleanField(default=False)
    is_paid = models.BooleanField(default=False)
    status = models.CharField(max_length=50, default="In process")

    class Meta:
        db_table = "Order"

    def __str__(self):
        return f"Order №{self.pk} | User {self.user.first_name} {self.user.last_name}"
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.SET_DEFAULT, null=True, default=None)
    name = models.CharField(max_length=150)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "order_item"

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.product.price_sale() * self.quantity, 2)
    
    def __str__(self):
        return f"Product {self.name} | Order №{self.order.pk}"

site/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True)
    phone_number = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return self.username

site/users/forms.py
from dataclasses import fields
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        "autofocus": True,
        'class': 'form-control',
        'placeholder': "Input username"
        }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
            "autocomplete": "current-password",
            'class': "form-control",
            'placeholder': "Input password",
            }),
    )
    class Meta:
        model = User
        fields = ['username', 'password',] 


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = {
            "first_name",
            "last_name",
            "username",
            'email',
            "password1",
            "password2",
        }

    first_name = forms.CharField()        
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()        
    password2 = forms.CharField()


class UserProfileForm(UserChangeForm):

    class Meta:
        model = User()
        fields = {
            'image',
            'first_name',
            'last_name',
            'username',
            'email',
        }
    image = forms.ImageField(required=False)
    first_name = forms.CharField()        
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    

site/users/views.py
from django.contrib import auth, messages
from django.db.models import Prefetch
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from traitlets import Instance
from django.contrib.auth.decorators import login_required

from orders.models import Order, OrderItem
from users.forms import UserLoginForm, UserProfileForm, UserRegistrationForm
from cart.models import Cart
# Create your views here.

def login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            
            session_key= request.session.session_key

            if user:
                auth.login(request, user)
                messages.success(request, "Succesfully logged")

                if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)
                
                redirect_page = request.POST.get('next', None)
                if redirect_page and redirect_page != reverse('user:logout'):
                    return HttpResponseRedirect(request.POST.get('next'))
                
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()

    context = {   
        'form': form     
    }    
    return render (request, 'users/login.html', context)

@login_required
def logout(request):
    auth.logout(request) 
    messages.success(request, "Succesfully logged out")    
    return redirect(reverse('main:index'))


def registration(request):
    if request.method == "POST":
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid(): 

            session_key= request.session.session_key

            form.save()
            user = form.instance
            auth.login(request, user)

            if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)

            messages.success(request, "Succesfully registered and logged in")
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()

    context = {  
        'form': form      
    }    
    return render (request, 'users/registration.html', context)

@login_required
def profile(request):
    if request.method == "POST":
        form = UserProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():            
            form.save() 
            messages.success(request, "Succesfully changed")           
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = UserProfileForm(instance=request.user)
    
    orders = (
        Order.objects.filter(user=request.user)
        .prefetch_related(
            Prefetch(
                "orderitem_set",
                queryset=OrderItem.objects.select_related('product'),
            )
        )
        .order_by("-id")
    )

    context = { 
        'form': form,
        'orders': orders       
    }    
    return render (request, 'users/profile.html', context)


def users_cart(request): 
    return render (request, 'users/users_cart.html')

site/users/templates/users/login.html
{% extends "layout.html" %}
{% load static %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock  %}

{% block page_content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                    <h2 class="text-center mb-4">Login</h2>
                    <form action="{% url "user:login" %}" method="post">
                        {% csrf_token %}  
                        <input type="hidden" name="next" value={{ request.GET.next }}>                                           
                        <div class="mb-3">
                            <label for="{{ form.username.id_for_label }}" class="form-label">Username</label>
                            {{ form.username }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.password.id_for_label }}" class="form-label">Password</label>
                            {{ form.password }}
                        </div>                        
                        <button type="submit" class="btn btn-dark btn-block">Log in</button>                        
                    </form> 
                    
                    <div class="mt-3">
                        <a href="#">Forget password?</a> | <a href="{% url "users:registration" %}">New accout</a>
                    </div>
                    <hr>
                    <div class="text-center">
                        <p>Or log in using:</p>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static "files/icons/google.svg" %}" alt="Catalog Icon" width="16" height="16">
                            Google
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static "files/icons/facebook.svg" %}" alt="Catalog Icon" width="16" height="16">
                            Facebook
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static "files/icons/github.svg" %}" alt="Catalog Icon" width="16" height="16">
                            GitHub
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock  %}

                    
                   
                

site/users/templates/users/profile.html
{% extends "layout.html" %}
{% load static %}

{% load cart_tags %}


{% block head %}
<title>Handmade - User profile</title>
{% endblock %}

{% block page_content %}
{% user_carts request as carts %}

<div class="row">
    <div class="container mt-5">
        <div class="row">
            <!-- Profile with userdata -->
            <div class="col-md-5">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">User profile</h3>
                    <form action="{% url "user:profile" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12 mb-3 text-center">
                                {% if  user.image %}
                                <img src="{{ user.image.url }}"
                                    alt="Avatar" class="img-fluid rounded-circle"
                                    style="max-width: 150px;">
                                {% else %}
                                <img src="{% static "files/images/baseavatar.jpg" %}"
                                    alt="Avatar" class="img-fluid rounded-circle"
                                    style="max-width: 150px;">
                                {% endif %}                                
                                <input type="file" class="form-control mt-3" id="id_image" name="image"
                                    accept="image/*">
                                {% if form.image.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">
                                        {{ form.image.errors }}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_first_name" class="form-label">First name*</label>
                                <input type="text" class="form-control" id="id_first_name" name="first_name"
                                    placeholder="First name" value="{{ form.first_name.value }}" required>
                                {% if form.first_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">
                                        {{ form.first_name.errors }}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_last_name" class="form-label">Last name*</label>
                                <input type="text" class="form-control" id="id_last_name" name="last_name"
                                    placeholder="Last name" value="{{ form.last_name.value }}" required>
                                {% if form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">
                                        {{ form.last_name.errors }}
                                    </div>
                                {% endif %}
                            </div>
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_username" class="form-label">Username</label>
                                <input type="text" class="form-control" id="id_username" name="username"
                                    placeholder="Username" value="{{ form.username.value }}" required>
                                {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                {% endif %}
                                    
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email" name="email"
                                    placeholder="E-mail *youremail@example.com" value="{{ form.email.value }}"
                                    required>
                                {% if form.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                {% endif %}
                            </div>
                           <button type="submit" class="btn btn-dark">Save</button>
                        </div>
                         
                    </form>
                </div>            
            <!-- Cart -->            
            <div class="col-md-7">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Cart</h3>
                    <div class="container" id="cart-items-container">
                        <!-- Cart layout -->
                            {% include "cart/include/included_cart.html" %}
                        <!-- End of cart layout -->
                    
                   
                </div>
            </div>
            <!-- Order making -->
            <div class="col-md-12">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">My orders</h3>
                    <!-- Orders layout -->
                    <div class="container">
                        <div class="accordion" id="accordionExample">
                            {% for order in orders %}                        
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading{{ order.id }}">
                                    <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}" aria-expanded="false" aria-controls="collapse{{ order.id }}">
                                        Order №{{ order.id }} - {{ order.created_timestamp }} | Status:<strong class="mx-2">{{ order.status }}</strong>
                                    </button>
                                </h2>
                                <div id="collapse{{ order.id }}" class="accordion-collapse collapse{% if order == orders.0 %} show{% endif %}" aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Product</th>
                                                    <th>Amount</th>
                                                    <th>Price</th>
                                                    <th>Total price</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for item in order.orderitem_set.all %}
                                                    <tr>
                                                        <td><a class="text-white" href="{% url "goods:product" item.product.slug %}">{{ item.product.name }}</a></td>
                                                        <td>{{ item.quantity }}</td>
                                                        <td>{{ item.price }} $</td>
                                                        <td>{{ item.products_price }} $</td>
                                                        
                                                    </tr>                                                
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                        <div class="d-flex justify-content-between">
                                            <p><strong>Total</strong></p>
                                            <p><strong>255.00 $</strong></p>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}                            
                        </div>
                    </div>
                    <!-- Закончилась разметка заказов -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

site/users/templates/users/registration.html
{% extends "layout.html" %}
{% load static %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock  %}

{% block page_content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">New account</h2>
                <form action="{% url "user:registration" %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_firstName" class="form-label">Name*</label>
                            <input type="text" class="form-control" id="id_firstName" name="first_name"
                            value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                placeholder="Enter your first name" required>
                            {% if form.first_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_lastName" class="form-label">Last name*</label>
                            <input type="text" class="form-control" id="id_lastName" name="last_name"
                            value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                placeholder="Enter your last name" required>
                            {% if form.last_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_username" class="form-label">Username*</label>
                            <input type="text" class="form-control" id="id_username" name="username"
                            value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                placeholder="Choose username" required>
                            {% if form.username.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Email*</label>
                            <input type="email" class="form-control" id="id_email" name="email"
                            value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                placeholder="E-mail" required>
                            {% if form.email.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password1" class="form-label">Password*</label>
                            <input type="password" class="form-control" id="id_password1" name="password1"
                                placeholder="Enter password" required>
                            {% if form.password1.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password2" class="form-label">Password repeat*</label>
                            <input type="password" class="form-control" id="id_password2" name="password2"
                                placeholder="Repeat password" required>
                            {% if form.password2.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                            {% endif %}
                        </div>
                    </div>
                    <button type="submit"
                        class="btn btn-dark btn-block">Create account</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

site/users/templates/users/users_cart.html
{% extends "layout.html" %}
{% load static %}
{% load cart_tags %}


{% block page_content %}

<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                <h3 class="text-center mb-4">Cart</h3>
                <div class="container" id="cart-items-container">
                    {% user_carts request as carts %}
                    <!-- Cart layout -->
                    {% include "cart/include/included_cart.html" %}                   
                     
                    {% comment %} {% if carts %}                   
                        <a class="btn btn-dark" href="{% url "orders:create_order" %}">
                            Order
                        </a>
                    {% endif %} {% endcomment %}
                    
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}