site/app/urls.py
from re import DEBUG
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),  
    path('user/', include('users.urls', namespace='user')), 
    path('cart/', include('cart.urls', namespace='cart')), 
    path('orders/', include('orders.urls', namespace='orders')),   
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG :
    urlpatterns += debug_toolbar_urls() 

site/goods/urls.py
from django.urls import path
from . import views

app_name='goods'

urlpatterns = [        
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),     
]

site/main/urls.py
from django.urls import path
from . import views

app_name='main'

urlpatterns = [    
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
     
]

site/users/urls.py
from django.urls import path
from . import views

app_name='users'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('registration', views.registration, name="registration"),
    path('profile', views.profile, name="profile"),
    path('logout', views.logout, name="logout"),
    path('users-cart/', views.users_cart, name="users_cart"),
]

site/templates/layout.html
{% load static %}
{% load tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "files/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "files/css/my_css.css"%}">
    <!--Footer style for main page -->
    {% block  head %}
    {% endblock  %}

    <!-- Favicons for different platforms -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "files/favicon/apple-touch-icon.png"%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "files/favicon/favicon-32x32.png"%}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "files/favicon/favicon-16x16.png"%}">
    <link rel="manifest" href="{% static "files/favicon/site.webmanifest"%}">    
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'main:index' %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                               Information
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="#">Delivery and payment</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Contacs</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url 'main:about' %}">About us</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="{% url "user:users_cart" %}">Cart</a>
                        </li>
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link  text-white" href="{% url "users:login" %}">Log in</a>
                            </li>                        
                        {% else %}
                            <li class="nav-item dropdown ">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    Profile
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item  text-white" href="{% url "user:users_cart" %}">Cart</a></li>
                                    <li><a class="dropdown-item  text-white" href="{% url "users:profile" %}">Personal account</a>
                                    </li>
                                    {% if user.is_admin or user.is_staff %}
                                        <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Admin</a></li>
                                    {% endif %}
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item  text-white" href="{% url "users:logout" %}">Log out</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                    <form action="{% url "catalog:search" %}" method="get" class="d-flex" role="search">
                        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- Catalog and cart with fixed position on a page -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Catalog -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Catalog
                        <img class="mx-1" src="{% static "files/icons/grid-fill.svg"%}" alt="Catalog Icon" width="16"
                            height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        
                        {% tag_all_categories as categories %}
                        {% for category in categories %}
                            <li><a class="dropdown-item text-white" href="{% url 'catalog:index' category.slug %}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- Cart icon calls separate window -->
                {% block modal_cart %}                
                {% endblock  %}
                <!-- End of cart window -->
            </div>
        </div>
        <!-- Content -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Empty (for now) block -->
                </div>
                <div class="col-lg-10">
                    {% include "includes/notifications.html" %}
                    
                    {% block page_content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </section>  
   

    {% block footer %}
    {% endblock %}
    <script src={% static "files/js/jquery/jquery-3.7.0.min.js" %}></script>    
    <script src={% static "files/js/jquery-ajax.js" %}></script>
    <script src={% static "files/js/bootstrap/bootstrap.bundle.min.js" %}></script>
</body>

</html>